missevia/two-tomatoes

app/controllers/chefs_controller.rb, app/views/chefs/index.html.erb, config/routes.rb, test/controllers/chefs_controller_test.rb
=> created index method and view

app/views/devise/registrations/new.html.erb, config/routes.rb, db/migrate/20190820100836_add_name_to_user.rb, db/schema.rb
=> Added name to users

config/routes.rb
=> Added Moritzs line that was deleted due to merge conflicts earlier

app/controllers/bookings_controller.rb, config/routes.rb, db/schema.rb
@AhmadMajid , could you please check if all looks good?
=> Changed booking form redirection path to users profile

app/controllers/bookings_controller.rb, app/views/bookings/show.html.erb, config/routes.rb
@AhmadMajid I added a booking show page, created respective method 'show' in controller & added a new route.
=> Booking show page

app/controllers/chefs_controller.rb, app/policies/chef_policy.rb, config/routes.rb, db/schema.rb
=> Fixed some issues with Chef

app/views/reviews/_form.html.erb
Added reviews form in views. May need to delete the create.html.erb and new.html.erb later?
Pinging @akellos @greentea-latte @missevia for review
=> Added reviews form in views

app/assets/stylesheets/components/_card.scss, app/views/chefs/index.html.erb, app/views/layouts/application.html.erb, db/schema.rb
=> Style index and show page

app/policies/chef_policy.rb
Added admin stuff.
ping @akellos @greentea-latte @missevia for review.
=> added admin stuff

app/controllers/bookings_controller.rb, app/models/user.rb, app/policies/booking_policy.rb, app/policies/chef_policy.rb
=> Fixing evias bookings with pundit

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_navbar.scss, app/views/pages/home.html.erb, db/schema.rb
=> Frontend test

app/controllers/chefs_controller.rb, app/policies/chef_policy.rb
Now a user doesn't have to be logged in when visiting chefs/index or chefs/show!
@missevia
=> Fixed index and show permissions

app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/pages/_chef-show.scss, app/assets/stylesheets/pages/_index.scss, app/views/chefs/index.html.erb, app/views/chefs/show.html.erb
=> styled chef show page

app/assets/stylesheets/components/_card.scss
=> changed card css

Gemfile, Gemfile.lock, db/seeds.rb
I added some seeds. This will create 20 random users and some chefs with different names and ratings. Make sure to bundle install before running db:seed!
@AhmadMajid @greentea-latte @missevia
=> Created a seeds with users and chefs

app/controllers/application_controller.rb, app/controllers/bookings_controller.rb, app/controllers/users_controller.rb, app/models/user.rb, app/views/chefs/show.html.erb, app/views/devise/registrations/new.html.erb, app/views/users/show.html.erb, config/initializers/devise.rb, config/routes.rb, db/schema.rb
ping @akellos 
Fixed the devise error & added the correct path from chef's profile to booking page
=> Fixed devise error that did not allow user to sign up

app/views/devise/registrations/new.html.erb, db/migrate/20190821095042_add_image_to_user.rb, db/schema.rb, db/seeds.rb
=> Add image to user

app/assets/stylesheets/components/_avatar.scss, app/views/chefs/index.html.erb, app/views/chefs/show.html.erb
Both pages will now display the actual images (no placeholders anymore)! Tested it!
@AhmadMajid @missevia
=> Added Images to Index an Chefs profile

app/assets/stylesheets/pages/_users_show.scss, app/views/users/show.html.erb
=> User profile

app/assets/stylesheets/components/_alert.scss, app/assets/stylesheets/components/_navbar.scss, app/views/chefs/index.html.erb, app/views/chefs/show.html.erb, app/views/layouts/application.html.erb, app/views/pages/home.html.erb
Added image to navbar (if user is not logged in, no image will be displayed)! Tested it!
@AhmadMajid @missevia
=> Improve navbar

app/views/users/show.html.erb
=> Linked user profile and booking show page

app/assets/stylesheets/components/_card.scss, app/views/layouts/application.html.erb, app/views/pages/home.html.erb
=> Small changes in images (navbar) and css fix

app/views/chefs/show.html.erb, app/views/layouts/application.html.erb
Footer is shown on all pages except show chef
@missevia
=> Fixed footer

app/controllers/bookings_controller.rb, app/views/bookings/new.html.erb, app/views/bookings/show.html.erb
added date to form, changed date formatting to remove time, and made it display on bookings page
pinging @missevia @akellos for review
=> Adding date

app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/components/_card.scss, app/views/chefs/show.html.erb
=> Added fake reviews to chef show

app/views/layouts/application.html.erb
Added logout to the navbar. 
Fixed navbar 'become a chef' issue. 
@AhmadMajid @akellos please review :)
=> Fixed navbar become a chef button and implemented logout logic

Gemfile, Gemfile.lock, app/assets/stylesheets/pages/_home.scss, app/controllers/chefs_controller.rb, app/models/chef.rb, app/views/chefs/index.html.erb, config/routes.rb
@missevia @akellos @AhmadMajid
=> added simple search bar for cuisine

app/controllers/application_controller.rb
Users can now add an image Url and it will be saved when signing up. Tested it!
=> Fixed the issue with the sign up image

db/seeds.rb
Added some user seeds for pitch and testing....
=> Add user seeds

app/views/chefs/show.html.erb
=> Real reviews are now displayed on chef show

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/pages/_become_chef_page.scss, app/assets/stylesheets/pages/_index.scss, app/controllers/chefs_controller.rb, app/views/chefs/new.html.erb, app/views/layouts/application.html.erb, app/views/layouts/playground.html.erb, db/migrate/20190822104620_add_price_to_chefs.rb, db/schema.rb
Created 'Become a chef' table. 
Added price to chefs. 
Please do DB migrate once you pull from master branch
ping @AhmadMajid @akellos @greentea-latte for review
=> Made become a chef table

app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/pages/_chef-show.scss, app/views/chefs/show.html.erb
fixed chef show page layout and added responsiveness
=> fixed chef show layout issues

app/controllers/application_controller.rb, app/views/devise/registrations/new.html.erb, db/migrate/20190822142404_add_address_to_users.rb, db/schema.rb
Added address to user
Pinging @missevia @akellos @greentea-latte for review
=> Adding address to user

db/seeds.rb
=> Added some seeds for reviews

app/views/bookings/show.html.erb
added price to bookings need text after after .chef.price %> and before the h4>.  or everything gets shifted to left for some reason.
Pinging @akellos @greentea-latte @missevia for review.
=> Adding price to bookings

Gemfile, Gemfile.lock, app/assets/stylesheets/pages/_home.scss, app/assets/stylesheets/pages/_new_booking.scss, app/views/bookings/new.html.erb, app/views/pages/home.html.erb, config/initializers/geocoder.rb
=> Booking form

app/views/layouts/application.html.erb
Fixed double notice when you book a chef, only top is visible now.
Ping @akellos @missevia @greentea-latte for review.
=> Fixing alerts

app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/pages/_chef_index.scss, app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_log_in.scss, app/assets/stylesheets/pages/_sign_up.scss, app/views/chefs/index.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb
Did some basic formatting to log in and sign up forms. Still needs some work.
=> Basic forms

app/views/reviews/new.html.erb
pinging @akellos @greentea-latte @missevia for review
=> fixed review form so you can only give a rating from 1 to 5

app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/pages/_sign_up.scss, app/assets/stylesheets/pages/_users_show.scss, app/views/bookings/show.html.erb, app/views/chefs/index.html.erb, app/views/layouts/application.html.erb, app/views/users/show.html.erb
=> Fixed footer issue and made a profile show page

app/views/chefs/show.html.erb
Fixed an issue with chef show (wasn't working when user isn't logged in). Works now!
@AhmadMajid @greentea-latte @missevia
=> Small fix on chef show

app/assets/stylesheets/components/_navbar.scss, app/views/layouts/application.html.erb
Look out for the jumping tomatoes!
=> Jump around

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/pages/_home.scss, app/assets/stylesheets/pages/_log_in.scss, app/assets/stylesheets/pages/_new_booking.scss, app/assets/stylesheets/pages/_sign_up.scss, app/views/pages/home.html.erb
ping @akellos 
I made the buttons consistent and fixed some small layout issues on various pages
=> Made buttons consistent and fixed layout issues

app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/pages/_chef_index.scss, app/controllers/chefs_controller.rb
=> fixed profile avatar size

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/pages/_chef_index.scss, app/controllers/chefs_controller.rb, app/views/chefs/index.html.erb
@missevia @akellos @AhmadMajid
=> Add responsiveness to index page

app/assets/stylesheets/pages/_chef-show.scss, app/views/chefs/show.html.erb, app/views/layouts/application.html.erb
Fixed margin top on chef show page
=> Made small fixes

app/assets/stylesheets/components/_map.scss, app/controllers/chefs_controller.rb, app/javascript/plugins/init_autocomplete.js, app/javascript/plugins/init_mapbox.js, db/migrate/20190823113945_add_coordinates_to_users.rb
=> Index is now sorted

app/assets/stylesheets/pages/_users_show.scss
@AhmadMajid @akellos @missevia
=> added responsiveness to user show
